import turtle
import math
turtle.setworldcoordinates(-400,0,400,800)
turtle.shape("turtle")
szer=600
wys=200
szer_drzwi=50
wys_drzwi=90
zolw=turtle.Pen()
zolw.speed(1)
turtle.forward(szer)
turtle.left(90)
turtle.forward(wys)
turtle.left(45)
turtle.forward(szer/math.sqrt(2))
turtle.left(90)
turtle.forward(szer/math.sqrt(2))
turtle.right(45)
turtle.backward(szer)
turtle.forward(600)
turtle.left(90)
turtle.forward(wys)
turtle.left(90)
turtle.forward(275)
turtle.left(90)
turtle.forward(wys_drzwi)
turtle.right(90)
turtle.forward(szer_drzwi)
turtle.right(90)
turtle.forward(wys_drzwi)
turtle.done()